// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dotenv from "dotenv";

function parse(param) {
  var parsed = Dotenv.config().parsed;
  console.log(parsed);
  console.log(parsed.INPUT_PATH);
  console.log(parsed.OUTPUT_GIT_REPO);
  console.log(parsed.OUTPUT_FOLDER);
  return parsed;
}

export {
  parse ,
  
}
/* dotenv Not a pure module */
