// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dotenv from "./Dotenv.mjs";
import * as SimpleGit from "simple-git";

function commitFiles(inputPath, outputGitRepo, outputFolder) {
  console.log("inputPath=" + inputPath);
  console.log("outputGitRepo=" + outputGitRepo);
  console.log("outputFolder=" + outputFolder);
  var options = {
    baseDir: "/Users/whit/Projects/temp/test3",
    binary: "git"
  };
  var git = SimpleGit.simpleGit(options);
  console.log(git);
  var u = git.init(false);
  console.log(u);
  
}

function main(param) {
  var inputPath = Dotenv.get("INPUT_PATH");
  var outputGitRepo = Dotenv.get("OUTPUT_GIT_REPO");
  var outputFolder = Dotenv.get("OUTPUT_FOLDER");
  if (inputPath !== undefined && outputGitRepo !== undefined && outputFolder !== undefined) {
    return commitFiles(inputPath, outputGitRepo, outputFolder);
  } else {
    console.log("Invalid .env config");
    return ;
  }
}

main(undefined);

export {
  commitFiles ,
  main ,
  
}
/*  Not a pure module */
